server:
  port: 8080
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 60s
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/snapadmin
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
  security:
    user:
      name: admin
      password: admin

snapadmin:
  enabled: true
  modelsPackage: mingu.spring.snapadmin.entity
  baseUrl: admin